### ISSUE TITLE
Problem with launch

### ISSUE THREAD

**Issue by Ladanovasv** [vlmaps/vlmaps#10]
![image](https://github.com/vlmaps/vlmaps/assets/47398458/eabf2cc8-8d4a-42e8-9d1e-b5a70f879104)
How do i solve this problem?

**Comment by Tom-Huang** [comment]
did you manage to visualize the RGB and semantics of the demo dataset?

**Comment by Ladanovasv** [comment]
Yes, I had this problem when I try to launch on my data.

**Comment by Tom-Huang** [comment]
could you share the whole error message?

**Comment by Tom-Huang** [comment]
I haven't received the response so I will close it for now. Reopen the issue once you get further question.
