### ISSUE TITLE
About semantic

### ISSUE THREAD

**Issue by Ladanovasv** [vlmaps/vlmaps#11]
How did you prepare semantic?

**Comment by Tom-Huang** [comment]
the semantic is generated through the LSeg encoder. You can check the function below to see how LSeg encoder convert an RGB image to pixel-wise embedding: [https://github.com/vlmaps/vlmaps/blob/bc79b26a577e5a9408f86e45e5c16530ca80f867/examples/clip_mapping_lseg_from_scratch_batch.py#L204](https://github.com/vlmaps/vlmaps/blob/bc79b26a577e5a9408f86e45e5c16530ca80f867/examples/clip_mapping_lseg_from_scratch_batch.py#L204)

**Comment by Ladanovasv** [comment]
Thank you.

**Comment by Tom-Huang** [comment]
my pleasure. Once you have further questions, feel free to reopen the issue again.
