### ISSUE TITLE
How to apply vlmaps to practical environment navigation

### ISSUE THREAD

**Issue by Jessy-Huang** [vlmaps/vlmaps#13]
I am trying to use the ROS car to create a real environment vlmaps and navigate on this basis. I see that your paper has also been implemented in a practical environment, but lacks specific implementation details. May I know which algorithm you used to implement navigation? Is it SLAM? How can we combine the sensing data seen by robots with LLM?

**Comment by Tom-Huang** [comment]
> May I know which algorithm you used to implement navigation?
The navigation part is done by first converting the language instruction into a list of python API calls like "move_to(object_name)", "move_to_left(object_name)", etc. Inside those APIs, we implement (1) the indexing step to determine the object_name's position in the map as the goal position, (2) a global planning algorithm like A* to compute the path from the current robot pose (assume that a localization algorithm can provide the correct robot pose) to the goal position, and (3) compute a list of discrete actions (turn left/right 5 deg, forward 0.25m) to control the robot to follow the path.

> Is it SLAM?
SLAM is used for creating a map while localizing the robot. In the (2) step of the description above, we assume that there is a localization module that can provide the accurate robot pose relative to the VLMap we build. We used RTABMap (a RGBD SLAM package) for the localization.

> How can we combine the sensing data seen by robots with LLM?
During the navigation, we only use the observation (RGBD) to localize the robot. After getting the initial pose of the robot in the map, we no longer rely on the observation for navigation. It means that once we generated the path and the discrete actions list in (2) and (3), we simply execute them and do not adjust based on the observation.
