### ISSUE TITLE
pos[1] += camera_height is it right？

### ISSUE THREAD

**Issue by Jessy-Huang** [vlmaps/vlmaps#14]
# read pose
        pos, rot = load_pose(pose_path)  # z backward, y upward, x to the right
        rot_ro_cam = np.eye(3)
        rot_ro_cam[1, 1] = -1
        rot_ro_cam[2, 2] = -1
        rot = rot @ rot_ro_cam
        pos[1] += camera_height

should it be：
pos[2] += camera_height

**Comment by Tom-Huang** [comment]
In the code, we use the default robot coordinate frame that Habitat-Sim uses: z backward, x right, y up. So the position of the camera relative to the robot frame should be `camera_height` above the robot frame (in y direction), so the last line of the code is `pos[1] += camera_height`
