### ISSUE TITLE
How to use habitat to build my own vlmaps dataset

### ISSUE THREAD

**Issue by Jessy-Huang** [vlmaps/vlmaps#16]
According to your paper ”we use the Habitat simulator with the Matterport3D dataset for the evaluation of multi-object and spatial goal navigation tasks”. You obtained a large dataset using habitat。

![c9cda9726fb72c19105f9bbda5ddc20](https://github.com/vlmaps/vlmaps/assets/66520966/9eb3d1e6-52f8-40b8-81d1-be3300c2324a)

I have already built the habitat simulation environment, but I can only run a simple demo based on the documentation. I would like to use other datasets from matterport3D to collect several datasets in Habitat and compare the results with real datasets.

In the paper, there is not much description on how to use the Habitat dataset to build one's own dataset. Can you provide some tips on this work?

**Comment by Tom-Huang** [comment]
I will release the full code soon! There you can find the code to create your own dataset.
