### ISSUE TITLE
Optimizing vlmaps using sam

### ISSUE THREAD

**Issue by Jessy-Huang** [vlmaps/vlmaps#17]
Excuse me for your valuable time, I have encountered the following issues:
In the dataset of the real scene, I found that the vlmap obtained from the real dataset has the following problems: unclear boundaries, unclear edges of objects with sharp edges in the map, and some scattered pixels that do not belong to entities. Considering the excellent performance of [sam](https://github.com/facebookresearch/segment-anything) I am considering using SAM to optimize the model.
My idea is to replace this function: [get_lseg_feat](https://github.com/vlmaps/vlmaps/blob/master/examples/clip_mapping_lseg_from_scratch_batch.py#L151)
this function returns a vector of shape of (1, 512, 347, 520), However, sam obtains multiple masks for a single image, each composed of True and False, with True representing the foreground and False representing the background, forming the representation of the object and the black and white image。 just as follow：
mask：
`[[False, False, False, ..., False, False, False],

         [False, False, False, ..., False, False, False],

         [False, False, False, ..., False, False, False],

         ...,

         [False, False, False, ..., False, False, False],

         [False, False, False, ..., False, False, False],

         [False, False, False, ..., False, False, False]]`

picture:
![img_v2_4186f21f-a2a8-430d-a070-b805462d397g](https://github.com/vlmaps/vlmaps/assets/66520966/946de3a4-1ef7-46ce-9893-275976afda18)

I encountered difficulties in this step, and what I am currently confused about is:

1. Is the idea of using SAM to optimize vlmap feasible

2. Replace get_lseg_feat Is the idea of the feature function feasible

If you have any suggestions, please give me more guidance. Thank you very much

**Comment by Tom-Huang** [comment]
I think the idea is valid.
