### ISSUE TITLE
Missing planning_utils.py filea

### ISSUE THREAD

**Issue by Jessy-Huang** [vlmaps/vlmaps#20]
https://github.com/vlmaps/vlmaps/blob/master/vlmaps/controller/continuous_nav_controller.py#L6 imports the planning_utils， but under the vlmaps/utils/ folder, there is not a  planning_utils.py file

**Comment by Tom-Huang** [comment]
I just pushed a quick fix. It should be `mapping_utils` rather than `planning_utils`.
