### ISSUE TITLE
MatterPort3D

### ISSUE THREAD

**Issue by ChrisWanghb** [vlmaps/vlmaps#26]
May I ask which part of the MatterPort3D dataset do you need to support the vlmap?

**Comment by Tom-Huang** [comment]
The names of the Matterport3D scenes are listed in our dataset: `https://drive.google.com/file/d/1KaRi1VnY7C_TT1WckDWxHvP4v3MTNu1a/view?usp=sharing`. Those scenes are: [5LpN3gDmAk7, JmbYfDe2QKZ, UwV83HsGsw3, Vt2qJdWjCF2, YmJkqBEsHnH, gTV8FGcVJC9, jh4fc5c5qoQ, mJXqzFtmKg4, ur6pFq6Qu1A]

**Comment by Tom-Huang** [comment]
if you have the matterport3D download script, use the following command to download: 
```
# download the data at the current directory
python2 download_mp.py -o . --task habitat
```
