### ISSUE TITLE
Top-down maps of the scene

### ISSUE THREAD

**Issue by chengzu-li** [vlmaps/vlmaps#27]
Thanks for your fantastic work and I'm really interested in it. May I know if there is any possible way to obtain the golden top-down view of each scene directly from the .glb or .ply file with habitat-sim? Thanks!

**Comment by Tom-Huang** [comment]
If you installed `habitat-sim` from conda and installed `habitat-lab` from source from github repo [https://github.com/facebookresearch/habitat-lab](https://github.com/facebookresearch/habitat-lab), you can generate the top down view with this function [https://github.com/facebookresearch/habitat-lab/blob/da51b4c3319faa043fcf90806b4f08ee4e9645e3/habitat-lab/habitat/utils/visualizations/maps.py#L404](https://github.com/facebookresearch/habitat-lab/blob/da51b4c3319faa043fcf90806b4f08ee4e9645e3/habitat-lab/habitat/utils/visualizations/maps.py#L404). For more details, you can check habitat's website.
