### ISSUE TITLE
multi-robot navigation

### ISSUE THREAD

**Issue by ChrisWanghb** [vlmaps/vlmaps#29]
How to build open-vocabulary obstacle maps from a list of obstacle categories for different robot embodiments for multi-robot navigation?

**Comment by Tom-Huang** [comment]
An example is shown in [generate_obstacle_map.py](https://github.com/vlmaps/vlmaps/blob/master/application/generate_obstacle_map.py). By calling `customize_obstacle_map` method in the class `VLMap` (see [here](https://github.com/vlmaps/vlmaps/blob/master/vlmaps/map/vlmap.py#L157)), you can provide a list of potential obstacle names and a list of real obstacle names among the potential names to create an open-vocabulary obstacle map. The customized obstacle map is saved in the attribute `obstacles_new_cropped` in `VLMap`.
