### ISSUE TITLE
Intuition  behind what is being done in all these lines ?

### ISSUE THREAD

**Issue by Lazyass66** [vlmaps/vlmaps#30]
# read pose
        pos, rot = load_pose(pose_path)  # z backward, y upward, x to the right
        rot_ro_cam = np.eye(3)
        rot_ro_cam[1, 1] = -1
        rot_ro_cam[2, 2] = -1
        rot = rot @ rot_ro_cam
        pos[1] += camera_height

        pose = np.eye(4)
        pose[:3, :3] = rot
        pose[:3, 3] = pos.reshape(-1)

        tf_list.append(pose)
        if len(tf_list) == 1:
            init_tf_inv = np.linalg.inv(tf_list[0])

        tf = init_tf_inv @ pose

**Comment by Tom-Huang** [comment]
when we load the pose from the pose file, we actually load the pose of the robot in the habitat-sim coordinate. In that coordinate frame, the forward direction is -z, right is x, upward is y. But in the usual case, the camera frame has forward as z, right is x, upward is -y. We want to transform the robot pose to camera pose, that is why we apply `rot_ro_cam` to the loaded pose. In the lower part of the code, we want to treat the first camera pose as the origin of our map: we compute the inverse of the first camera pose and multiply the inverse of the first camera pose with all later pose to get the relative pose to the first camera frame.
