### ISSUE TITLE
[Question] What was the process for collecting the poses?

### ISSUE THREAD

**Issue by sairitwik27** [vlmaps/vlmaps#32]
Hi, I am trying to extend the VLMaps for other scenes in the MP3D dataset. I was wondering how the poses were collected? Did you just send the agent on a random walk, or were any exploration algorithms used?

**Comment by Tom-Huang** [comment]
I collected the walk manually. What you need is just to implement a keyboard-controlled agent in habitat-sim and walk to every corner of the scene.
