### ISSUE TITLE
[Question] Right and Left notion

### ISSUE THREAD

**Issue by hjorthchristian** [vlmaps/vlmaps#34]
Hello I have a question, 

Does the notion of left and right comes from the image the robot is seeing right now? Or is it related to the orientation of the robot from its other sensors? When specify objects/landmarks you want to move to, or close to, do you ONLY take the spatial map with landmarks or do you also take the camera image to do so? What you view as pros and cons for each method?

Thanks for your time, and you've made a great work!

**Comment by Tom-Huang** [comment]
the left and right are relative to the current image observation direction. For the navigation, we only perform global planning, namely using the top-down obstacle map and the target location to perform A* search and generate a path consisting of a list of 2d positions on the top-down map. Then we generate a list of actions consisting of "turn left", "turn right" and "move forward" based on the path and execute it strictly without adapting it to the current image observation.

**Comment by Tom-Huang** [comment]
feel free to open the issue again if your question persists.
