### ISSUE TITLE
[Question] Navigation JSON file 

### ISSUE THREAD

**Issue by vcozzolino** [vlmaps/vlmaps#35]
I built a map using a matterport3d scene which is not part of the examples in this repo. I wanted to try the `object _goal_navigation.py` script but I'm confused about how to populate the `object_navigation_tasks.json`.
In particular, I don't understand the purpose of the `objects_info` field... why would we need to provide row/col value for objects that are in the scene? Isn't this something that should be taken care of by the VLM using the instruction text and knowledge of the scene?

**Comment by Tom-Huang** [comment]
we wrote an interactive matplotlib interface to collect the object goal dataset. The idea is to visualize the top-down GT semantic map and manually select a sequence of points on the target objects. The `row` and `col` indicate the selected positions on the GT semantic map. However, in our evaluation, we only used the semantic labels of those selected points. The final evaluation does not use the `row` and `col` values. We used the habitat-sim's GT data to access the locations of those target objects.
