### ISSUE TITLE
Off the shelf navigation stack

### ISSUE THREAD

**Issue by sairitwik27** [vlmaps/vlmaps#4]
I was going through the vlmaps paper, and was trying to find the off the shelf navigation stack that converts code as policies part of the code to habitat smulator. I couldn't find it in the github repository, are there any plans to release the code for it to be able to reproduce the results?

**Comment by Tom-Huang** [comment]
I appreciate your interest in our paper. We are refactoring the code now. We will release the code soon.

**Comment by juexZZ** [comment]
Hi @Tom-Huang @mees,
Just want to follow up on this. Are you still planning to share the codes for navigation? 
This is a very interesting work and many colleagues in my research community would love to play with it and cite your paper if we can have access to the navigation stack. :)

**Comment by Tom-Huang** [comment]
we just release the navigation stack the the rest of the dataset. Feel free to try it out!
