### ISSUE TITLE
How is vlmaps_dataset.zip generated?

### ISSUE THREAD

**Issue by seusofthd** [vlmaps/vlmaps#41]
Asking this because I wanna to test with a new scene where we have both depth, RGB and pose info of the mobile robot. I got confused on how is the vlmaps_dataset generated.

**Comment by Tom-Huang** [comment]
sorry for the delay. Regarding the data generation, we manually control a robot in the habitat-sim to collect exploration data (RGB, depth, robot pose etc.). The `generate_dataset.py` code downloads the pre-collected trajectories (only poses) in 10 different scenes in habitat-sim + Matterport3D and places an agent at those poses to generate the observations (RGBD). If you want to collect your own data in habitat-sim, we just update a script to collect your own data: [here](https://github.com/vlmaps/vlmaps/blob/master/dataset/collect_custom_dataset.py). Please follow the instruction in readme to collect your own data: [Collect your own data in Habitat-Sim](https://github.com/vlmaps/vlmaps/tree/master?tab=readme-ov-file#collect-your-own-data-in-habitat-sim).
