### ISSUE TITLE
Where is "convert_habitat_pos_list_to_cropped_map_pos_list"?

### ISSUE THREAD

**Issue by soumajm** [vlmaps/vlmaps#42]
`convert_habitat_pos_list_to_cropped_map_pos_list` is called in [robot/habitat_lang_robot.py](https://github.com/vlmaps/vlmaps/blob/d394bff70c57823c6dfd20827f7f73696fcd5d78/vlmaps/robot/habitat_lang_robot.py#L161C54-L161C102) but I could not find the function definition.

**Comment by Tom-Huang** [comment]
sorry for the confusion. During the refactoring, we forgot to remove this method `load_gt_region_map`. It is calling some functions' names before the refactoring. That's why you couldn't find the `convert_habitat_pos_list_to_cropped_map_pos_list`. To achieve the same function now, you can do:
```python
cropped_map_pos_list = []
for habitat_pos in habitat_pos_list:
    habitat_tf = np.eye(4)
    habitat_tf[:3, 3] = np.array(habitat_pos).flatten()
    self.vlmaps_dataloader.from_habitat_tf(habitat_tf)
    row, col, theta_deg = self.vlmaps_dataloader.to_cropped_map_pose()
    cropped_map_pos_list.append([row, col])
```
