### ISSUE TITLE
openai.error.InvalidRequestError: The model `text-davinci-002` has been deprecated

### ISSUE THREAD

**Issue by Neal2020GitHub** [vlmaps/vlmaps#44]

**Comment by weiyunpei** [comment]
hello, for me, I changed all the `engine="text-davinci-002"` to `engine="gpt-3.5-turbo-instruct"` .

**Comment by Tom-Huang** [comment]
Thank you for your interest in our project. We noticed that this was because our original code relied on the old version of the OpenAPI. We have updated our code to support the newer version of the OpenAI API.
