### ISSUE TITLE
Issue of resolution

### ISSUE THREAD

**Issue by Moon-heart** [vlmaps/vlmaps#45]
When I followed the instructions to change w:1080 to 540 and h:720 to 360 in data_cfg.resolution.w and data_cfg.resolution.h to collect data, then ran creat_map.py and index_map.py, I found that I couldn't correctly build the map. Are there other places that need to be modified? Can you help me answer my questions? How should I lower the resolution, and is there a limit to the lowest resolution?

**Comment by Tom-Huang** [comment]
you need to change the intrinsic matrix correspondingly here: https://github.com/vlmaps/vlmaps/blob/master/config/map_config/vlmaps.yaml#L10C23-L10C24
