### ISSUE TITLE
Index_map too slow

### ISSUE THREAD

**Issue by Bluedask** [vlmaps/vlmaps#47]
When I run "python index_map.py", the progarm is taking too much time in the "o3d.visualization.draw_geometries([pcd])" (serveral hours) and it cannot finish function "visualize_rgb_map_3d". Therefore, I cannot input the corresponding query to "input("What is your interested category in this scene?")". Is this really time-consuming or I make some mistakes?
<img width="354" alt="image" src="https://github.com/vlmaps/vlmaps/assets/40200549/a3e62a6a-ac0a-433d-a1b4-84c6fcce076d">
<img width="267" alt="image" src="https://github.com/vlmaps/vlmaps/assets/40200549/4a63d900-a71f-404e-8b57-ffd40c166290">

**Comment by Tom-Huang** [comment]
Hi, thank you for your interest in our project. Have you try to visualize some other point clouds with similar point numbers? Do they also take such a long time?

**Comment by Bluedask** [comment]
Sorry to be late, I w

**Comment by Bluedask** [comment]
Sorry for the late reply. I have been working on other projects for the past few weeks. I will test your suggestions this week, and if I get any results, I will share them.

**Comment by Bluedask** [comment]
Previously, I was using Ubuntu without a desktop environment. After switching to Ubuntu with a desktop environment, everything seems to have normalized. Thank you for your response.
