### ISSUE TITLE
semantic arrays and `obj2cls_dict.txt`

### ISSUE THREAD

**Issue by DiTo97** [vlmaps/vlmaps#5]
What is the content of the semantic arrays and `obj2cls_dict.txt` stored in the dataset? Are those necessary to create the VL map of a real unseen environment or were they necessary only for model ablation as mentioned in Appendix D of the paper?

**Comment by Moon-heart** [comment]
hi, I also want to known the content of the semantic arrays and obj2cls_dict.txt stored in the dataset? Are these just for visualization purposes, and do they not affect map building?
