### ISSUE TITLE
AI2-THOR 

### ISSUE THREAD

**Issue by xiaolu-luu** [vlmaps/vlmaps#51]
I tested in the AI2-THOR  simulation environment, but the effect is very poor, what may be the reason? Can you provide the test code in the AI2-THOR  simulation environment mentioned in the paper? How to collect data in AI2-THOR simulation environment?

![ScreenCapture_2024-06-02-20-54-13](https://github.com/vlmaps/vlmaps/assets/82944479/efdd557d-5503-4bd4-99c3-3ef1de0da76a)

**Comment by xiaolu-luu** [comment]
![ScreenCapture_2024-06-02-21-52-05](https://github.com/vlmaps/vlmaps/assets/82944479/c0b679ac-a4a2-4bf6-8bad-226c890cb4c9)
What might be the cause of this?Why can one wall be aligned, but the side walls can't be aligned？Thank you very much

**Comment by Tom-Huang** [comment]
It looks like something is wrong with the transformation and poses. Could you share a code snippet to reproduce this?

**Comment by xiaolu-luu** [comment]
`  base2cam_rot: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  base_forward_axis: [0, 0, 1]
  base_left_axis: [-1, 0, 0]
  base_up_axis: [0, -1, 0]`
Originally, I changed the coordinate change to the same as you answered in another question, and later I tried to change it to the following to achieve the alignment effect,But why is this happening?Thanks for your reply!
`  base2cam_rot: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  base_forward_axis: [0, 0, -1]
  base_left_axis: [-1, 0, 0]
  base_up_axis: [0, 1, 0]`
![ScreenCapture_2024-06-05-14-05-16](https://github.com/vlmaps/vlmaps/assets/82944479/5a2b9dbf-ff9c-4347-9719-dcf4b8c817e6)

**Comment by Tom-Huang** [comment]
I think it is because that in AI2THOR, the robot base coordinate frame has the same orientation as the camera (z forward, x right, y downward).

**Comment by Tom-Huang** [comment]
I tested the following config and it works for AI2THOR with the main branch: ```base2cam_rot: [1, 0, 0, 0, 1, 0, 0, 0, 1] base_forward_axis: [0, 0, -1] base_left_axis: [-1, 0, 0] base_up_axis: [0, 1, 0]```. I will mark this as solved. If there is further question, please reopen the issue.
