### ISSUE TITLE
About obj2cls_dict.txt file 

### ISSUE THREAD

**Issue by HowoongJun** [vlmaps/vlmaps#54]
Hi, thanks for your nice work. 

In the obj2cls_dict.txt file of your sample dataset, what is the first column of the txt file? it is from 0~468, and it is indexed in the https://github.com/vlmaps/vlmaps/blob/bc79b26a577e5a9408f86e45e5c16530ca80f867/utils/clip_mapping_utils.py#L114

**Comment by Tom-Huang** [comment]
the semantic image generated from the habitat-sim is not semantic label but instance id. The obj2cls dictionary is converting the instance ids to semantic ids.

**Comment by HowoongJun** [comment]
I understand. It is the instance ids from mp3d dataset's semantic information right?

**Comment by Tom-Huang** [comment]
yes exactly
