### ISSUE TITLE
ModuleNotFoundError: No module named 'vlmaps.utils' how to setup??

### ISSUE THREAD

**Issue by dw-kwack** [vlmaps/vlmaps#55]
In the VLMap Creation section, this error happened. Please how can I fix it? 
i want run this project in local pc not jupyter notebook
Thank you
-------------------------------------
python generate_dataset.py

Traceback (most recent call last):
  File "generate_dataset.py", line 14, in <module>
    from vlmaps.utils.habitat_utils import get_obj2cls_dict, make_cfg, save_obs
ModuleNotFoundError: No module named 'vlmaps.utils'

**Comment by korayaykor** [comment]
What was the solution?

**Comment by qwer137559** [comment]
same questions ，how to solve 。thanks

**Comment by Tom-Huang** [comment]
Thanks for the interest in our project. Could you try running `pip install -e .` under the root directory and try again?
