### ISSUE TITLE
How to Generate the Poses.txt For Different Scenes?

### ISSUE THREAD

**Issue by korayaykor** [vlmaps/vlmaps#57]
Currently working on this repo, generating rgb, depth, pose semantic and obj2cls_dict folders and images and it works flawlessly. But how can I generate this file for the episodes that doesn't have poses.txt file in the drive link?

**Comment by Tom-Huang** [comment]
which folder doesn't have the poses.txt file?

**Comment by Tom-Huang** [comment]
Related to #59
