### ISSUE TITLE
identical semantics  in different locations（相同的语义在不同位置）

### ISSUE THREAD

**Issue by vpnasdfghjkl** [vlmaps/vlmaps#7]
How to handle the case of two identical semantics in different locations？（如何处理两个在不同位置的相同的语义呢？）

**Comment by Tom-Huang** [comment]
VLMaps currently doesn't support instance segmentation so it doesn't distinguish ambiguous goals (e.g. two chairs might share the same semantic labels). In theory, we can apply clustering to separate points with the same labels but we haven't implemented that.
